platform :ios, '9.0'

# The target name is most likely the name of your project.
target 'RNBaiduMap' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'react-native-baidumap-sdk', path: '../lib/ios'
end

